Vagrant.configure(2) do |config|
  config.vm.define "ubuntupreseedvm" do |ubuntupreseedvm|
    ubuntupreseedvm.vm.box = "ubuntu/bionic64"
    ubuntupreseedvm.vm.hostname = "UbuntuPreseedVM"
  end

  # To automatically configure a private network uncomment following line.
  # config.vm.network "private_network", ip: "192.168.1.xx"

  config.vm.provider "virtualbox" do |vb|
  # Customize the amount of CPU and memory on the VM:
     vb.cpus = "1"
     vb.memory = "1024"
  end
  # Port forwarding: If unneeded comment or remove following lines
  config.vm.network "forwarded_port", guest: 22, host: 2204
  config.vm.network "forwarded_port", guest: 80, host: 8004
  config.vm.network "forwarded_port", guest: 443, host: 4443
end